### ISSUE TITLE
недочёты в CSS

### ISSUE THREAD

**Issue by godunko-mikhail** [BVN4/igc.su#1]
### navbar:
текст не по центру
![Снимок](https://user-images.githubusercontent.com/97464195/172081515-7f0da419-800e-4729-ab05-d6a82c5c498f.PNG)

Выпадающие окно прозрачное?
![Снимок](https://user-images.githubusercontent.com/97464195/172082721-4addd944-62bf-4cb7-b08c-5f181cac4f64.PNG)

### /senate:
иконки не по центру
![Снимок](https://user-images.githubusercontent.com/97464195/172081886-7ab9bcc6-570d-4c4e-ab30-8925aadf033f.PNG)

нет отступа между меню и контентом
![Снимок](https://user-images.githubusercontent.com/97464195/172082247-905de499-6dc5-4820-963b-54622c7c6e9b.PNG)

СЛИШКОМ мелко
![Снимок](https://user-images.githubusercontent.com/97464195/172082860-788e3f9a-1a8d-4408-b635-3578d5c82ff4.PNG)

### /levels
текст под меню
![Снимок](https://user-images.githubusercontent.com/97464195/172082430-b76e38ee-b82c-49c6-8e95-109300f30dab.PNG)

много ненужного места внизу страницы
![image](https://user-images.githubusercontent.com/97464195/172083089-622fd14b-8a12-414e-a007-38356ce86bc1.png)
### /elections/2022-04
иконки налазят на верхний текст
![image](https://user-images.githubusercontent.com/97464195/172083244-4a9a25e1-4e1e-4f30-9e70-cec0720b5b7d.png)

**Comment by ruskotwo** [comment]
Добрый день!
Спасибо за внимание к нашему проекту. Почти все проблемы с навбаром связаны с переходом на SASS. При переходе был утерян CSS код, отвечающий за навбар. Вскоре будет исправлено. 

Что касается "/senate", эта страница через какое то время будет переосмыслена и переделана полностью.
